[postgres]
host = "localhost" # or 'postgres' if using docker-compose
port = "5432"
db = "your_database_name"
user = "your_username"
password = "your_password"

[mongo]
url = "mongodb://localhost:27017" # or 'mongodb://mongo:27017' if using docker-compose
db = "your_database_name"

[sqlite]
path = "your_path_for_local_db_file"
